---
- name: Change MOTD message
  hosts: web_servers
  become: yes

  tasks:
    - name: Create MOTD file if it does not exist
      file:
        path: /etc/motd
        state: touch

    - name: Get hostname and IP address of host
      delegate_to: localhost
      set_fact:
        host_details: "{{ ansible_hostname }} with IP {{ ansible_default_ipv4.address }}"

    - name: Update MOTD file with host details and greeting
      lineinfile:
        path: /etc/motd
        regexp: '.*'
        line: 'Hello, administrator! This is {{ host_details }}.'
